repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-yaml
      name: Check YAML files
    - id: check-toml
      name: Check TOML files
    - id: end-of-file-fixer
      name: Ensure proper file endings
    - id: trailing-whitespace
      name: Remove unnecessary whitespace from code
      args: [--markdown-linebreak-ext=md]
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: Sort Python imports with isort
      args:
        - --profile
        - black
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
    - id: black
      name: Format Python code with black
- repo: local
  hooks:
    - id: pylint
      name: Lint Python code with pylint
      entry: pylint
      language: system
      types: [python]
